const LOGIN = 'LOGIN';
const SET_QUESTION = 'SET_QUESTION';
const SET_SCORE = 'SET_SCORE';
const SET_ASSERTIONS = 'SET_ASSERTIONS';
const SET_TIMER = 'SET_TIMER';
const SET_ANSWERS = 'SET_ANSWERS';

export { LOGIN, SET_ANSWERS, SET_TIMER, SET_QUESTION, SET_SCORE, SET_ASSERTIONS };
